### ISSUE TITLE
Show a notification to instruct users to download new hosts

### ISSUE THREAD

**Issue by reagle** [Frederick888/external-editor-revived#109]
I noticed the latest version says: "Run a messaging host health check upon start". Will this then tell us the message host needs to up date because TB/plugin have? If so, that's fantastic. I haven't seen it yet, but does it contain a link so we can easily download the latest host? This will make managing updates a bit easier -- until MacOS folks get a homebrew with the extension and host together #35 😉 .

**Comment by Frederick888** [comment]
> Will this then tell us the message host needs to up date because TB/plugin have?

No, but that sounds like a good idea.

> but does it contain a link so we can easily download the latest host?

I'm not too crazy about this. It's not very straightforward to implement (https://bugzilla.mozilla.org/show_bug.cgi?id=1190681) and the Releases page's link doesn't change anyway.

**Comment by Frederick888** [comment]
Just realised that (some?) HTML can actually be used in notification messages, e.g. `browser.notifications.create('', { 'type': 'basic', 'title': 'Hello!', 'message': '<a href="https://example.com">example</a>' })`. So yeah, I'll see if I can do that as well.
