### ISSUE TITLE
Broken threads when replying

### ISSUE THREAD

**Issue by nicoroeser** [Frederick888/external-editor-revived#110]
# Description

Version 91f2118192ba09135da99983f4fb5552a3e04dfe breaks threads when used for replies: (at least) headers `In-Reply-To` and `References` are missing. IIRC, this worked before (but I am not sure about in which exact version; I could try to bisect it when that becomes important).

# Environment

- OS: tried on an up-to-date Ubuntu 20.04, but I doubt that it matters
- Thunderbird version: 102.8.0+build2-0ubuntu0.20.04.1
- ExtEditorR extension version: 0.6.0, built from commit 91f2118192ba09135da99983f4fb5552a3e04dfe
- `external-editor-revived --version` output: `External Editor Revived native messaging host for linux (x86_64) v0.6.0`
- Locale: `de_DE.UTF-8`

# Configuration

* Editor: gVim,
* no command template,
* no checkboxes in settings checked.

# Logs

From the error console:
`composeDetails.replyTo` is an empty array; I assume that is related.

# Screenshots

Not needed (mail without headers, threading broken, receivers/list members annoyed :slightly_frowning_face: ).

**Comment by Frederick888** [comment]
Thank you for help in testing!

Unless I am mistaken about how custom headers work, this is a bug in Thunderbird, and I've reported it to https://bugzilla.mozilla.org/show_bug.cgi?id=1824594. If it doesn't get addressed soon, I may have to disable this feature in the next release. For now I have #111.

`composeDetails.replyTo` is not related by the way. It controls the 'Reply-To' field which tells the recipient to which email address they should send their replies.

![image](https://user-images.githubusercontent.com/4507647/227779677-9573e202-3a0e-45cb-b15b-a07e2285a4d7.png)

**Comment by nicoroeser** [comment]
> Thank you for help in testing!

You’re very welcome! Thanks to you for this wonderful, time-saving extension!

> 
> Unless I am mistaken about how custom headers work, this is a bug in Thunderbird, and I've reported it to [bugzilla.mozilla.org/show_bug.cgi?id=1824594](https://bugzilla.mozilla.org/show_bug.cgi?id=1824594).

Thank you. About saving as draft: unsure. I think it is not necessary, but my Thunderbird is configured to auto-save every few minutes, and I am not totally sure what happened.

> If it doesn't get addressed soon, I may have to disable this feature in the next release. For now I have #111.

Great! (I mean the workaround, not possibly having to disable the feature.)

I have tested the current state (commit df1f8c216c356916da66cc691639b130386f1873) when replying to a message and editing it with the extension. The results were as I (and I assume, you as well) had expected:

| save as draft | custom headers | result |
|----|----|----|
| not explicitly (quite sure it was not auto-saved, but not 100% sure) | disabled | ✔ **(works)** |
| manually, before sending | disabled | ✔ **(works)** |
| not explicitly (quite sure it was not auto-saved, but not 100% sure) | enabled, one custom header added | ❌ **(fails)**: threading broken, custom header is present, `In-Reply-To` and `References` (and possibly others, not verified) are missing |

It does not matter much _for me_, because I do not need custom headers at the moment. Thanks for the workaround. :smiley:

> 
> `composeDetails.replyTo` is not related by the way. It controls the 'Reply-To' field which tells the recipient to which email address they should send their replies.

Ah, I see. I thought this might be the case, but was not able to understand the code immediately. Thanks for clarifying! :thumbsup:

**Comment by Frederick888** [comment]
Could you please check, when you do have custom headers, whether this is still an issue with TB 115?

**Comment by Frederick888** [comment]
I tested it with TB 115 and I couldn't reproduce this issue any more.
