### ISSUE TITLE
wiki: English Screenshot of Registry Editor

### ISSUE THREAD

**Issue by lorenzleutgeb** [Frederick888/external-editor-revived#115]
Feel free to use the following (slightly less confusing) screenshot for

https://github.com/Frederick888/external-editor-revived/wiki/Windows#installing-the-native-messaging-host

![regedit](https://user-images.githubusercontent.com/542154/233305707-013d4901-a548-46ca-9aa1-cb1a84e57a7c.png)

**Comment by Frederick888** [comment]
Wiki updated. Thank you.
