### ISSUE TITLE
Line breaks created by 

### ISSUE THREAD

**Issue by weierophinney** [Frederick888/external-editor-revived#142]
# Description

Newlines created within the external editor are not honored when returning to the TB compose screen. Instead, they are all merged to a single, wrapped line.

If I spawn the external editor again, it shows the line breaks correctly.

I have tried switching between `\n` and `\r\n` for line breaks, but with no success.

# Environment

- OS:Linux
- Thunderbird version: 115.6.0
- ExtEditorR extension version: 1.0.0
- `external-editor-revived --version` output: 1.0.0

# Configuration

- Editor: Custom
- Shell: sh
- Command template: `/home/username/.local/bin/neovide --neovim-bin /home/username/.local/bin/nvim --no-fork "path/to/temp.eml"`
- Suppress help headers: selected
- Temporary directory: `/home/username/tmp`

# Logs

```text
ExtEditorR sending:  
Object { configuration: {…}, tab: {…}, composeDetails: {…} }
​
composeDetails: Object { from: "Matthew Weier O'Phinney <email@example.com>", overrideDefaultFcc: false, type: "new", … }
​​
additionalFccFolder: ""
​​
attachVCard: false
​​
attachments: Array []
​​
bcc: Array []
​​
body: '<!DOCTYPE html>\n<html><head>\n<meta http-equiv="content-type" content="text/html; charset=UTF-8"></head><body>This is a test.\n\nDo we see line breaks?\n\nPlease?\n</body></html>'
​​
cc: Array []
​​
customHeaders: Array []
​​
deliveryFormat: "plaintext"
​​
deliveryStatusNotification: false
​​
followupTo: Array []
​​
from: "Matthew Weier O'Phinney <email@example.com>"
​​
identityId: "id1"
​​
isPlainText: false
​​
newsgroups: Array []
​​
overrideDefaultFcc: false
​​
overrideDefaultFccFolder: null
​​
plainTextBody: "This is a test. Do we see line breaks? Please?"
​​
priority: "normal"
​​
relatedMessageId: null
​​
replyTo: Array []
​​
returnReceipt: false
​​
subject: ""
​​
to: Array []
​​
type: "new"
​​
<prototype>: Object { … }
​
configuration: Object { version: "1.0.0", shell: "sh", template: '/home/username/.local/bin/neovide --neovim-bin /home/username/.local/bin/nvim --no-fork "/path/to/temp.eml"', … }
​
tab: Object { id: 8, index: 0, windowId: 103, … }
​
<prototype>: Object { … }
[background.js:118:11](moz-extension://8c2388f3-d97c-4835-a844-0b9007561e1a/background.js)
ExtEditorR received:  
Object { configuration: {…}, warnings: [], tab: {…}, composeDetails: {…} }
[background.js:138:11](moz-extension://8c2388f3-d97c-4835-a844-0b9007561e1a/background.js)
```

# Screenshots

External editor:

![image](https://github.com/Frederick888/external-editor-revived/assets/25943/547bb5d9-e901-4844-8c78-78cd446ef369)

On return to TB:

![image](https://github.com/Frederick888/external-editor-revived/assets/25943/715778c3-d40b-4533-b3cd-48d0eb2babce)

**Comment by Frederick888** [comment]
> isPlainText: false

https://github.com/Frederick888/external-editor-revived/wiki#plain-text-emails

Or use `<br/>`.
