### ISSUE TITLE
Neovide option uses non-existent CMD flag --nofork

### ISSUE THREAD

**Issue by ekorchmar** [Frederick888/external-editor-revived#143]
# Description
Neovide external editor does not start with default config. `--nofork`should be replaced with `--no-fork`. When changed manually under "Custom" list option, works as expected.

# Environment

- OS: Arch Linux (btw)
- Thunderbird version: Thunderbird 115.6.1
- ExtEditorR extension version: 1.0.0
- `external-editor-revived --version` output: External Editor Revived native messaging host for linux (x86_64) v1.0.0

# Configuration

Default with neovide option chosen.

# Logs
Error is displayed by external app, no trace in logs.

# Screenshots
![image](https://github.com/Frederick888/external-editor-revived/assets/32364416/d764db2a-04bb-41f7-a066-1f263638c838)

**Comment by Frederick888** [comment]
Thanks for the report! It seems that this was changed in https://github.com/neovide/neovide/commit/5743356d654dbeaf213c0da3e2988c4d89c218e1#diff-4583b895d17596f30dcbac33a7d47de9c210df2c07210bb0775b7c27097345daR55. I'll update the template in the next release.

**Comment by Frederick888** [comment]
Thanks again. https://github.com/Frederick888/external-editor-revived/commit/4805a1d1e0ada1a581583be6bdd0af9e6a974107 is in the tree now.
