### ISSUE TITLE
Composing html emails without html

### ISSUE THREAD

**Issue by davdent** [Frederick888/external-editor-revived#151]
Feature request: 

Would it be possible to have an option so that writing html emails does not require the user to deal with html coding, but instead,  would send the unformatted lines of text to TB, respecting user line breaks. This could function as if one simply cut and pasted paragraphs of text -- with line breaks separating paragraphs -- into the TB Write window. 

For replied portion of replied emails, the html could stay as is.  Something like this would be extremely useful for me, as I am obliged to send html emails, I want to use my favourite text editor, but I definitely do not want to compose in html. 

Thanks for this wonderful extension.

**Comment by Frederick888** [comment]
This is much too niche.

Most of the users just write plain text emails; a handful use HTML when they work with email templates or something.

You're free to write a custom script yourself to extend EER.
