### ISSUE TITLE
Mac installation instructins

### ISSUE THREAD

**Issue by reagle** [Frederick888/external-editor-revived#16]
thunderbird: 102.0.1 (auto_updates) on macOS 12.4 21F79 arm64

Hello,

Fantastic to see this! I tried to follow the instructions but was confused.

1. If we install via addons.thunderbird, do we still have to install the messaging host? (How, then, to keep the versions in sync?)
2. Which path should the messaging host be placed in?
3. Is it correct that when editing the JSON file, we need to specify the path to the extension, which, if installed via addons, is `/Users/reagle/e/clear/data/tbird-reagle/extensions/external-editor-revived@tsundere.moe.xpi`
4. Also, you might want a step staying that to run the executable, the user will have to go into security preferences and permit the file to open, and then grant permission to open.
5. (And I still don't see a button in my editor window. If I did, can I associate it with a keyboard shortcut?)
6. Does the external editor need to wait?
7. 
<img width="687" alt="Screen Shot 2022-07-08 at 10 33 55" src="https://user-images.githubusercontent.com/596814/178018021-b1173676-e0fb-4b56-a64d-c4cfee726605.png">

**Comment by Frederick888** [comment]
Hate to be the RTFW person but a lot of these questions are already
answered by the wiki, and I can also only answer by copying the wiki
contents over. So I suggest you read the wiki carefully again. I'll
answer things that are not in wiki here.

---
> user will have to go into security preferences and permit the file to
> open, and then grant permission to open

I don't remember seeing this. You probably need to do an `xattr -c
./macos-latest-native-messaging-host.zip` after you download it.

---
> If we install via addons.thunderbird, do we still have to install the
> messaging host?

This is not wiki, but in https://addons.thunderbird.net/en-GB/thunderbird/addon/external-editor-revived/:

> Please visit Wiki for details about the companion native messaging
> host that's ***required*** for the extension to work.

I reckon this is pretty clear.

---
> How, then, to keep the versions in sync?

Manually.

If you install from addons.thunderbird.net, usually the extension will
update first. Then you'll see a notification telling you your messaging
host is outdated when you use it. So this is when you'll need to come
here and download the latest one.

---
> Does the external editor need to wait?

I don't know what `subl` is but basically you need to make sure your
editor blocks rather than forking into the background.

**Comment by Frederick888** [comment]
> I don't think you'd do it to the zip file, but to the file that results from unzipping the zip file?

IIRC files from an archive inherit the archive's xattr's? I'm not that familiar with macOS's access control. Anyway, this is not relevant to this project.

> > This is not wik
> 
> I'd make that clear on the wiki.
> 
> > Manually.
> 
> I'd make that clear on the wiki.

I added a note to https://github.com/Frederick888/external-editor-revived/wiki.

> That's sublime text. This could be on the wiki too.

You are welcome to share your setup in [Discussions](https://github.com/Frederick888/external-editor-revived/discussions). I'd like to keep the wiki as concise as possible.

Same goes if you use any undocumented terminals. I can probably in the future add links from wiki to Discussions posts tho.

---

Then answering questions I didn't answer last time

> Which path should the messaging host be placed in

Doesn't really matter, as long as you have the correct absolute path to it in your manifest JSON file. So simply copy it to somewhere you like, run the program, and the JSON printed out will automatically have the correct path for you. If the path is wrong, please open an issue and I'll see if I can figure it out.

> Is it correct that when editing the JSON file, we need to specify the path to the extension, which, if installed via addons, is /Users/reagle/e/clear/data/tbird-reagle/extensions/external-editor-revived@tsundere.moe.xpi

Again, the path points to where you save the native messaging host binary. If you followed the instructions, I don't think you even need to edit the JSON file.

> Also, you might want a step staying that to run the executable, the user will have to go into security preferences and permit the file to open, and then grant permission to open.

If you later do post to Discussions, can you upload a screenshot of this? I reckon that'll be more helpful to macOS users.

> And I still don't see a button in my editor window.

Either your window is too small and the button overflows, or somehow you need to manually right click on toolbar and find it in 'Customise'. Let me know the result and I can add something to the wiki.

> If I did, can I associate it with a keyboard shortcut?

At the moment no. https://webextension-api.thunderbird.net/en/91/commands.html _may_ be able to do this. You can open a separate feature request and I'll see if I can work it out.

**Comment by reagle** [comment]
BTW: if you wanted to do a [walkthrough](https://en.wikipedia.org/wiki/Cognitive_walkthrough) on a Mac installation, I'd be happy to share my time and my screen as I attempt to install it and get it working.

(I'm still running 68.12.1 because of the lack of external editor support, so it's not easy for me to try and tweak things, but I could backup everything, upgrade TB, and set aside time to do a walkthrough.)

**Comment by Frederick888** [comment]
Thunderbird is packed in macOS app container format I think? So AFAIK you can download the latest version, place it somewhere other than `~/Applications` or `/Application`, then you can have two copies at the same time.

And then in your Thunderbird data folder, find the `profiles.ini` file, change `StartWithLastProfile` to `0`.

```ini
[General]
StartWithLastProfile=0
```

Next time you open TB you'll be prompted to select or create a profile. This way you can have two profiles at the same time as well for different versions of TB.

Of cos definitely still do the backup just in case something goes wrong.

It'd be hard for me to do a real-time walkthrough. But since I haven't seen your full setup or logs from Error Console, it'd be nice if you can share every step you've done in details (how you installed the extension, where you saved the host binary, JSON manifest and its location, etc.).

And FWIW I suggest you test out your command template directly in terminal first as well, e.g. `sh -c '/opt/homebrew/bin/subl --wait "<any file>"'`. The command line must NOT return until sublime exits.

**Comment by ondohotola** [comment]
I also struggled a little, but after reading the wiki it was clear that that was an issue between chair and screen :-)-O

I use [https://alphacocoa.sourceforge.io/ ](url) by the way which comes with a command line tool `alphac` which has a wait option `-w`. 

I usually put that into /usr/local/bin, but using the complete location in the preferences
`/Applications/Alpha.app/Contents/Resources/alphac -w` works also very well.

If one wants to use emacs one can always use `aquamacs`, with server running and then `emacsclient` which also blocks

el

**Comment by reagle** [comment]
Tried again, starting with

	> cd ~/Downloads/
	> wget https://github.com/Frederick888/external-editor-revived/releases/download/v0.2.0/external-editor-revived-v0.2.0.xpi\nwget https://github.com/Frederick888/external-editor-revived/releases/download/v0.2.0/macos-latest-native-messaging-host-v0.2.0.zip\n
	> unzip macos-latest-native-messaging-host-v0.2.0.zip
	> chmod +x external-editor-revived
	> mkdir -p "$HOME/Library/Mozilla/NativeMessagingHosts"
	> ./external-editor-revived | tee "$HOME/Library/Mozilla/NativeMessagingHosts/external_editor_revived.json"
	> brew install thunderbird

Then adding the extension and configuring.

<img width="1229" alt="Screen Shot 2022-07-12 at 12 14 17" src="https://user-images.githubusercontent.com/596814/178549932-2a5c2658-17bb-4638-97b1-cbf708f2d41f.png">

<img width="694" alt="Screen Shot 2022-07-12 at 12 48 09" src="https://user-images.githubusercontent.com/596814/178549986-995bafc0-65b9-4b6a-a509-eae3190ce71e.png">

No sign of the button:

<img width="250" alt="Screen Shot 2022-07-12 at 12 48 37" src="https://user-images.githubusercontent.com/596814/178550037-ce8b7dd1-8cf6-4e30-b1fc-3895cf845de2.png">

Nor do I see anything in Tools.

<img width="547" alt="Screen Shot 2022-07-12 at 12 51 09" src="https://user-images.githubusercontent.com/596814/178550116-d2091dbc-6b42-4cff-9c4d-dc84606ae6e8.png">

I believe I have the prefs set correctly:

<img width="743" alt="Screen Shot 2022-07-12 at 12 52 08" src="https://user-images.githubusercontent.com/596814/178550187-cfca7f8c-0e72-411d-a190-3c5d11df724b.png">

And I think the JSON is correct:

<img width="708" alt="Screen Shot 2022-07-12 at 12 53 21" src="https://user-images.githubusercontent.com/596814/178550237-3e91d91d-dc8a-4a81-9089-2292237d59c7.png">

**Comment by ondohotola** [comment]
Find what does
find $HOME -name NativeMessagingHosts

show?

I found N existing one so I symlinked the parent (Mozilla) into ~/Library and put the json accordingly.

No drama on 12.4 arm64/x86 with the pure x86 and also with the (experimental) Universal.

I keep my binary in /usr/local/bin though. And I use sh instead of zsh in the preferences.

el


--
Dr. Eberhard W. Lisse \ / Obstetrician & Gynaecologist
***@***.*** / * | Telephone: +264 81 124 6733 (cell)
PO Box 8421 Bachbrecht \ / If this email is signed with GPG/PGP
10007, Namibia ;____/ Sect 20 of Act No. 4 of 2019 may apply

**Comment by reagle** [comment]
I can now get the External Editor button in the compose window by placing the JSON file here: `$HOME/Library/Application\ Support/Mozilla/NativeMessagingHosts/external_editor_revived.json`. This is the path suggested by the hint "Consult https://wiki.mozilla.org/WebExtensions/Native_Messaging for its location." **But** this is counter to the hint: "Under macOS this is usually ~/Library/Mozilla/NativeMessagingHosts/external_editor_revived.json".

Unfortunately, pressing the button does nothing.

**Comment by reagle** [comment]
The sequence that got me to the button is:

  brew install thunderbird
  cd ~/Downloads/
  wget https://github.com/Frederick888/external-editor-revived/releases/download/v0.2.0/external-editor-revived-v0.2.0.xpi
  wget https://github.com/Frederick888/external-editor-revived/releases/download/v0.2.0/macos-latest-native-messaging-host-v0.2.0.zip\n
  unzip macos-latest-native-messaging-host-v0.2.0.zip
  chmod +x external-editor-revived
  mkdir -p $HOME/Library/Application\ Support/Mozilla/NativeMessagingHosts
  external-editor-revived | tee $HOME/Library/Application\ Support/Mozilla/NativeMessagingHosts/external_editor_revived.json

The JSON file is:


  {
    "name": "external_editor_revived",
    "description": "Edit emails in external editors such as Vim",
    "path": "/Users/reagle/bin/external-editor-revived",
    "type": "stdio",
    "allowed_extensions": [
      "external-editor-revived@tsundere.moe"
    ]
  }

I'm not sure why the button doesn't work though, the editor configuration is as follows:

<img width="729" alt="Screen Shot 2022-07-12 at 15 22 30" src="https://user-images.githubusercontent.com/596814/178577049-29ed8368-088e-463a-a9c1-33130e36d4a8.png">

**Comment by reagle** [comment]
I reconfigured the editor as @Frederick888 suggested above -- and it does work in the terminal -- but still nothing happens when I press the button.

<img width="751" alt="Screen Shot 2022-07-12 at 15 30 55" src="https://user-images.githubusercontent.com/596814/178578787-9ff76545-89d2-4cfd-b025-a9fee9a78027.png">

I also notice this error in the log:

<img width="902" alt="Screen Shot 2022-07-12 at 15 30 16" src="https://user-images.githubusercontent.com/596814/178578851-3f01af7b-8edb-4c7d-961f-276d7e020622.png">

**Comment by reagle** [comment]
I tried moving the location of the host from my personal `~/bin` to `/usr/local/bin` but that didn't help.

{
    "name": "external_editor_revived",
    "description": "Edit emails in external editors such as Vim",
    "path": "/usr/local/bin/external-editor-revived",
    "type": "stdio",
    "allowed_extensions": [
      "external-editor-revived@tsundere.moe"
    ]
  }

**Comment by Frederick888** [comment]
I have to have a closer look at the feedback after work but regarding the manifest JSON location: https://github.com/mdn/content/pull/18086. I hope this can move forward asap and I can get rid of `Under macOS this is usually ~/Library/Mozilla/NativeMessagingHosts/external_editor_revived.json.`.

**Comment by Frederick888** [comment]
Suggestion I can give right now is that `No such native application` usually means you had manifest JSON in a wrong place (but this shouldn't impact whether you can see the button or not). If TB found the JSON, it should be some other kind of error message, e.g. (vaguely) 'does not exist' if JSON has a wrong file path, 'permission error' if you forgot to `chmod +x` it, etc.

Btw did you install TB to `/Applications` or `~/Applications`? If it was the former could you try

```sh
brew uninstall thunderbird
export HOMEBREW_CASK_OPTS="--appdir=~/Applications --fontdir=/Library/Fonts"
brew install --cask thunderbird
```

Just wondering if it's again some sort of obscure macOS security stuff doing its voodoo.

**Comment by Frederick888** [comment]
![image](https://user-images.githubusercontent.com/4507647/178637208-c5ed0428-e8e8-40d4-95a0-86c9095adb41.png)

^ And btw you don't need `sh -c` in the template itself, although it shouldn't harm. But there's a missing closing single quote in the end. It should be just `/opt/homebrew/bin/subl --wait "/path/to/temp.eml"`. (This is not related to the error you saw though.)

**Comment by Frederick888** [comment]
If you did install TB to `/Applications` as a system-wide app, which is Homebrew's default setting, I think my speculation above does sound plausible cos I just saw https://hg.mozilla.org/mozilla-central/file/012ceb5e65c2f22b19e921aedfe2aef311ea3631/toolkit/xre/nsXREDirProvider.cpp#l385

**Comment by reagle** [comment]
@Frederick888, thanks for the response. You are right about missing the single quote, I had corrected that without noting so here and have moved back to the command without `sh -c`. 

Also, I installed a version in `~/Applications` and that didn't help. I have a button, but clicking it did nothing adn I saw the same extension error.

**Comment by Frederick888** [comment]
@reagle Then I really don't have any idea then... 🤦

Your setting looked all good to me, especially the commands in [comment](https://github.com/Frederick888/external-editor-revived/issues/16#issuecomment-1182015928) were virtually identical to how I set things up on Mac.

Maybe just blindly pop a `external_editor_revived.json` file in all possible locations?

- `$HOME/Library/Application Support/Mozilla/NativeMessagingHosts/external_editor_revived.json`
- `$HOME/Library/Mozilla/NativeMessagingHosts/external_editor_revived.json`
- `/Library/Application Support/Mozilla/NativeMessagingHosts/external_editor_revived.json`
- `/Library/Mozilla/NativeMessagingHosts/external_editor_revived.json`

Or possibly some anti-virus? Thunderbird enterprise profile? Hmmmmmmmmmmmmmmmmm...

**Comment by reagle** [comment]
I'll hang tight and see how other Mac users fare.

**Comment by Frederick888** [comment]
Wait, you mentioned you were 'on macOS 12.4 21F79 arm64', is this M1? M1 shouldn't be able to use v0.2.0 binaries from my GitHub release though? Those binaries are for x86 Macs only atm

**Comment by ondohotola** [comment]
They work with Rosetta on mine

el


--
Dr. Eberhard W. Lisse \ / Obstetrician & Gynaecologist
***@***.*** / * | Telephone: +264 81 124 6733 (cell)
PO Box 8421 Bachbrecht \ / If this email is signed with GPG/PGP
10007, Namibia ;____/ Sect 20 of Act No. 4 of 2019 may apply

**Comment by reagle** [comment]
I took some time to try again this morning and got it to work!

Following the [same steps as above](https://github.com/Frederick888/external-editor-revived/issues/16#issuecomment-1182340657), I set TB (102.0.3) to use Rosetta.

<img width="252" alt="Screen Shot 2022-07-20 at 10 25 17" src="https://user-images.githubusercontent.com/596814/180010440-9ae1d74a-d855-4200-9628-16d019a31f7f.png">

This got me a bit further, with a different error.

<img width="881" alt="Screen Shot 2022-07-20 at 10 32 31" src="https://user-images.githubusercontent.com/596814/180010596-db475913-cabe-4510-8763-f42d4f7688ab.png">

Then configuring the location of the JSON file to `~/Library/Mozilla/NativeMessagingHosts/external_editor_revived.json` got it working.

Feel free to use my steps or screencaptures for Mac install instructions on the wiki.

**Comment by reagle** [comment]
My latest:

	cd ~/Downloads/
	wget https://github.com/Frederick888/external-editor-revived/releases/download/v0.3.0/external-editor-revived-v0.3.0.xpi
	wget https://github.com/Frederick888/external-editor-revived/releases/download/v0.3.0/macos-latest-native-messaging-host-v0.3.0.zip
	unzip macos-latest-native-messaging-host-v0.3.0.zip
	xattr -c ./external-editor-revived
	chmod +x ./external-editor-revived
	mv ./external-editor-revived ~/bin/
	mkdir -p ~/Library/Mozilla/NativeMessagingHosts/
	~/bin/external-editor-revived | tee ~/Library/Mozilla/NativeMessagingHosts/external_editor_revived.json
	# set /Applications/Thunderbird.app to open in Rosetta via Finder
	# launch Thunderbird and install XPI
	# configure command template as `/opt/homebrew/bin/subl --wait "/path/to/temp.eml"` ; click `Apply`

**Comment by ondohotola** [comment]
I must agree that on my M1 Airbook in TBird 91.11.0 the Update in
Tools -> Addons and Themes does not see the update, so one has to
manually download and install from file.

On my Intel boxes the upgrade is noticed and one only has to Check
for Updates.

external-editor-revived unzips already in mode 0755 and does not
require any attribute clearing.

As I wrote before you should look whether there is already one
NativeMessagingHosts directory, in my case there are

	$HOME/Library/Application Support/Mozilla/NativeMessagingHosts

and

	$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts
	$HOME/Library/Application Support/Google/Chrome Canary/NativeMessagingHosts

and I have symlinked the first one to

	$HOME/Library/Mozilla/NativeMessagingHosts

for consistency.

Why are you using backticks?

el


On 2022-07-20 20:21 , Joseph Reagle wrote:
 > My latest:
 >
 > cd ~/Downloads/
 > wget 
https://github.com/Frederick888/external-editor-revived/releases/download/v0.3.0/external-editor-revived-v0.3.0.xpi 

 > wget 
https://github.com/Frederick888/external-editor-revived/releases/download/v0.3.0/macos-latest-native-messaging-host-v0.3.0.zip 

 > unzip macos-latest-native-messaging-host-v0.3.0.zip
 > xattr -c ./external-editor-revived
 > chmod +x ./external-editor-revived
 > mv ./external-editor-revived ~/bin/
 > mkdir -p ~/Library/Mozilla/NativeMessagingHosts/
 > ~/bin/external-editor-revived | tee 
~/Library/Mozilla/NativeMessagingHosts/external_editor_revived.json
 > # set /Applications/Thunderbird.app to open in Rosetta via Finder
 > # launch Thunderbird and install XPI
 > # configure command template as
 > `/opt/homebrew/bin/subl --wait "/path/to/temp.eml"`
 > click `Apply`
[...]

-- 
Dr. Eberhard W. Lisse   \         /       Obstetrician & Gynaecologist
***@***.***             / *      |  Telephone: +264 81 124 6733 (cell)
PO Box 8421 Bachbrecht  \      /  If this email is signed with GPG/PGP
10007, Namibia           ;____/  Sect 20 of Act No 4 of 2019 may apply

**Comment by reagle** [comment]
backticks is just another level of quotation (markdown)

**Comment by reagle** [comment]
BTW: As an experiment, I'm now on TB 102.0.3 and I turned off Rosetta and this plugin (which I manually installed when running TB in Rosetta) and it continues to work! No idea, but TB is faster and this plugin works, so that's good news.

**Comment by Frederick888** [comment]
@reagle Good to know it worked! Though I wonder what changed? [Last time](https://github.com/Frederick888/external-editor-revived/issues/16#issuecomment-1182015928) you tested the same path but it didn't work. Hmm... Anyway, guess we can finally close this now :)

---

> I must agree that on my M1 Airbook in TBird 91.11.0 the Update in
> Tools -> Addons and Themes does not see the update, so one has to
> manually download and install from file.
>
> On my Intel boxes the upgrade is noticed and one only has to Check
> for Updates.

@ondohotola If you download the extension here it won't auto-update; it only auto-updates if you install from addons.thunderbird.net.
