### ISSUE TITLE
Text from the vim external editor not getting saved back to the Thunderbird editor upon exit

### ISSUE THREAD

**Issue by ngriffin7a** [Frederick888/external-editor-revived#19]
# Description

When I select the "vim" option, along with "Kitty" as the terminal, I am able to click on the "External Editor" toolbar button and see text like the following:

```
From: Neil Griffin <neil.griffin@myemail.xyz>
Subject: 
X-ExtEditorR-Send-On-Save: false
```

But when I edit the text with vim, and then exit with `:wq`, the text does not get saved back to the Thunderbird editor.

I tried changing the `X-ExtEditorR-Send-On-Save` value to `true` in the text (which I'm not sure if I should be doing) but that didn't help.

# Environment

- OS: macOs
- Thunderbird version: 91.2.0

# Configuration

vim

# Logs

There are no errors in the log.

**Comment by Frederick888** [comment]
Did you add a blank line above body?

And if you open Error Console first, you'll see what Thunderbird sends to the host and what the host sends back. What are the `plain_text_body` values in them?

**Comment by ngriffin7a** [comment]
First, I forgot to mention how super excited I am to see this project! Thanks so much @Frederick888 !

Looks like info is only being sent one way, meaning, from Thunderbird to vim. I don't see anything in the log coming from vim back to Thunderbird:
```
{
  "configuration": {
    "version": "0.1.1",
    "shell": "sh",
    "template": "/usr/local/bin/kitty --start-as=normal -- vim \"/path/to/temp.eml\"",
    "bypassVersionCheck": false
  },
  "tab": {
    "id": 12,
    "index": 0,
    "windowId": 191,
    "highlighted": true,
    "active": true,
    "status": "complete",
    "width": 1920,
    "height": 839,
    "type": "messageCompose",
    "mailTab": false
  },
  "composeDetails": {
    "from": "Neil Griffin <neil.griffin@myemail.xyz>",
    "to": [],
    "cc": [],
    "bcc": [
      "neil.griffin@myemail.xyz"
    ],
    "type": "new",
    "replyTo": [],
    "followupTo": [],
    "newsgroups": [],
    "subject": "",
    "isPlainText": true,
    "body": "<html><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><style></style></head><body style=\"font-family: -moz-fixed; white-space: pre-wrap;\"><br></body></html>",
    "plainTextBody": "",
    "attachments": []
  }
}
```

**Comment by Frederick888** [comment]
That's weird. It should at least send the original contents back unless it somehow crashed.

Did you see any regular logs in Error Console while doing this? e.g. `stderr output from native app external_editor_revived: ...`

Also make sure you're not filtering out any logs 
![image](https://user-images.githubusercontent.com/4507647/178061321-c632bc7f-f02b-40cc-bb41-83286c3303b3.png)

**Comment by Frederick888** [comment]
![image](https://user-images.githubusercontent.com/4507647/178061428-00f6bd06-d4e0-48a2-a304-373ce4f51312.png)
Something like this btw. Just added a random log in my local dev env.

And FWIW you can also test `sh -c '/usr/local/bin/kitty --start-as=normal -- vim "<any file>"'` to see if you can edit a random file this way.

**Comment by ngriffin7a** [comment]
After I applied the latest stable external-editor-revived from your recommendation in https://github.com/Frederick888/external-editor-revived/issues/20 it started working for me. However, I need to exit twice, meaning I need to do `:wq` from the Vim terminal window, then Kitty->Quit before I see the text show up back in the Thunderbird editor. No worries though, because I plan on using MacVim anyway. Great work @Frederick888 I really appreciate it! :)

**Comment by Frederick888** [comment]
Ah, you probably need to add `macos_quit_when_last_window_closed  yes` to your Kitty config. Can you confirm?

**Comment by Frederick888** [comment]
> Ah, you probably need to add `macos_quit_when_last_window_closed yes` to your Kitty config. Can you confirm?

I tested under macOS and this did look like the problem. Instead of adding more stuff to wiki, I plan to add this to Kitty's default command template instead. I'll probably also need to touch up the UI for a better migration process.

**Comment by ngriffin7a** [comment]
@Frederick888 I upgraded to v0.2.0 and verified that this issue is fixed. Thanks!
