### ISSUE TITLE
Custom MacVim editor: Unexpected property "relatedMessageId" for compose.setComposeDetails

### ISSUE THREAD

**Issue by ngriffin7a** [Frederick888/external-editor-revived#20]
# Description

I'm trying to use MacVim as my external editor for authoring a NEW message.

- Editor: Custom
- Shell: sh
- Command Template: /usr/local/bin/mvim "/path/to/temp.eml"

# Environment

- OS: macOS
- Thunderbird version: 91.2.0

# Configuration

MacVim

# Logs

This is what gets sent to MacVim:

```
{
  "configuration": {
    "version": "0.1.1",
    "shell": "sh",
    "template": "/usr/local/bin/mvim \"/path/to/temp.eml\"",
    "bypassVersionCheck": false
  },
  "tab": {
    "id": 14,
    "index": 0,
    "windowId": 207,
    "highlighted": true,
    "active": true,
    "status": "complete",
    "width": 1920,
    "height": 839,
    "type": "messageCompose",
    "mailTab": false
  },
  "composeDetails": {
    "from": "Neil Griffin <neil.griffin@myemail.xyz>",
    "to": [],
    "cc": [],
    "bcc": [
      "neil.griffin@myemail.xyz"
    ],
    "type": "new",
    "replyTo": [],
    "followupTo": [],
    "newsgroups": [],
    "subject": "",
    "isPlainText": true,
    "body": "<html><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><style></style></head><body style=\"font-family: -moz-fixed; white-space: pre-wrap;\"><br></body></html>",
    "plainTextBody": "",
    "attachments": []
  }
}
```

And this is what comes back:

```
{
  "configuration": {
    "version": "0.1.1",
    "sequence": 0,
    "total": 1,
    "sendOnSave": false,
    "bypassVersionCheck": false
  },
  "tab": {
    "id": 14,
    "index": 0,
    "windowId": 207,
    "highlighted": true,
    "active": true,
    "status": "complete",
    "width": 1920,
    "height": 839,
    "type": "messageCompose",
    "mailTab": false
  },
  "composeDetails": {
    "from": "Neil Griffin <neil.griffin@myemail.xyz>",
    "to": [],
    "cc": [],
    "bcc": [
      "neil.griffin@myemail.xyz"
    ],
    "type": "new",
    "relatedMessageId": null,
    "replyTo": [],
    "followupTo": [],
    "newsgroups": [],
    "subject": "asdf",
    "isPlainText": true,
    "plainTextBody": "qwert",
    "attachments": []
  }
}
```

And this is the error message:

> Error: Type error for parameter details (Unexpected property "relatedMessageId") for compose.setComposeDetails.

**Comment by Frederick888** [comment]
Oh according to https://webextension-api.thunderbird.net/en/91/compose.html#compose-composedetails, this field is only available from TB 91.3.1.

While I don't plan to deal too much with legacy TB problems, this seems to be an easy enough fix. Could download macos-latest-stable-native-messaging-host from https://github.com/Frederick888/external-editor-revived/actions/runs/2638234005, restart TB, and test it again?

**Comment by ngriffin7a** [comment]
@Frederick888 It works! Thanks!

I'm on the "release" update channel, and update regularly. So I was surprised to see you write "legacy". I see that version 102 is available from the thunderbird.net homepage. I wonder why the "release" update channel does not specify anything newer like version 102?

**Comment by Frederick888** [comment]
My work MacBook also on release channel got 102 a few days ago automatically. Considering you are not even using latest 91.x.x, maybe auto update is somehow broken? If it's also a work machine maybe IT blocked their update check server?

Anyway I'll merge the PR tomorrow and it'll in the next release. Thank you for reporting back.
