### ISSUE TITLE
Ctrl+e hotkey does not invoke the external editor

### ISSUE THREAD

**Issue by ngriffin7a** [Frederick888/external-editor-revived#22]
# Description

According to the [original exteditor project page](https://github.com/exteditor/exteditor), the Ctrl+e hotkey should invoke the external editor. Doesn't seem to be working for me -- I have to click the "External Editor" button instead. Seeing as how this is a tool that would be used by people that favor the keyboard over the mouse, it would be nice to have the hotkey working.

# Environment

- OS: macOS
- Thunderbird version: 91.2.0 

# Configuration

Custom, sh, /usr/local/bin/mvim

# Logs

No message in the logs.

**Comment by Frederick888** [comment]
I have #28 open for this. By the way was it Ctrl-E across all platforms?

**Comment by Frederick888** [comment]
Forgot to mention you can test before I merge by downloading from CI https://github.com/Frederick888/external-editor-revived/actions/runs/2641491781

I'll probably merge it tomorrow and get a new version out.

**Comment by ngriffin7a** [comment]
@Frederick888 I upgraded to v0.2.0 but sadly nothing happens when I press ctrl+e in the Thunderbird compose editor, nothing happens -- it does not popup the external editor. Also, nothing in the log.

**Comment by Frederick888** [comment]
https://github.com/Frederick888/external-editor-revived/wiki#keyboard-shortcut

On mac TB automatically overrides my Ctrl-E to Command-E, even if I explicitly define Ctrl-E for `mac`:

```diff
diff --git a/extension/manifest.json b/extension/manifest.json
index d68230f..4350f6e 100644
--- a/extension/manifest.json
+++ b/extension/manifest.json
@@ -49,9 +49,10 @@
     },
     "commands": {
         "_execute_compose_action": {
             "suggested_key": {
-                "default": "Ctrl+E"
+                "default": "Ctrl+E",
+                "mac": "Ctrl+E"
             },
             "description": "Edit in external editor"
         }
     },
```

I'm not aware any workaround of this but I guess Command prefix does feel more mac-ish...

If you _really_ want Ctrl-E I guess you can leverage Karabiner for it: https://github.com/pqrs-org/Karabiner-Elements/issues/808

**Comment by ngriffin7a** [comment]
@Frederick888 command+e is fine! Works great, thanks! :)
