### ISSUE TITLE
Cited text shows up as ordinary text after returning from external editor

### ISSUE THREAD

**Issue by nicoroeser** [Frederick888/external-editor-revived#39]
# Description

I’m experiencing the same issue as explained in exteditor/exteditor#66:

When the external editor opens, and you save the text and quit the external editor, all text shows up as “normal text”. Even lines that had been marked as cited before (blue on white in the default Thunderbird setup) become ordinary text lines, too (black on white in the default setup). The text loses its special properties with regards to line-breaking.

# Environment

- OS: Linux (Ubuntu focal 20.04.4 LTS)
- Thunderbird version: 91.9.1 (`1:91.9.1+build1-0ubuntu0.20.04.1`)
- ExtEditorR extension version: 0.2.0, built from 22d7774de494dd10899ac80903070b8f57b1aa85
- ExtEditorR host version: 0.2.0, built from 22d7774de494dd10899ac80903070b8f57b1aa85

# Configuration

- Editor: gVim

# Logs

Not relevant for this issue.

# Further information

This is all about plain text messages, not HTML.

Perhaps something like exteditor/exteditor#75 is helpful?

**Comment by nicoroeser** [comment]
@Frederick888 wrote:
> Interesting... So it's like 'Paste as Quotation' in UI.

Yes, but that should be done only for the actually quoted parts, of course.

> It's got nothing to do with things sent over the wire,

Sadly, this is incorrect: a proper quotation starts with `>` in the message source. If you just add such a sign at the start of a line, Thunderbird somehow prepends a space character.

Result: broken quoting on recipient side.

> but certainly is more visually appealing.

It is, but it is not only a visual effect, but changes the message body.

> Though I'm under the impression that this is not possible with MailExtension APIs.

Sigh, too bad. If you cannot reply to emails and use quoting, you’d destroy the workflow. :disappointed:

**Comment by Frederick888** [comment]
> Sadly, this is incorrect: a proper quotation starts with > in the message source. If you just add such a sign at the start of a line, Thunderbird somehow prepends a space character.
> 
> Result: broken quoting on recipient side.

I don't see this behaviour, i.e. spaces being added in front of `>`s.

![image](https://user-images.githubusercontent.com/4507647/178282607-cc09b726-537b-48f4-b205-9642ed142946.png)

As you can see, Thunderbird correctly parsed the email and treated 'Let's try it out.' as a cited section.

I also base64-decoded the message source and I didn't see such spaces.

**Comment by Frederick888** [comment]
And I think I can also test it by replying to the GitHub notification
directly. Let's give it a shot:

> Sadly, this is incorrect: a proper quotation starts with |>| in the message source. If you just add such a sign at the start of a line, Thunderbird somehow prepends a space character.
> 
> Result: broken quoting on recipient side.

-- 
Best regards,
Frederick Zhang

Email: ***@***.***
PGP:   8BFB EA5B 4C44 BFAC C8EC 5F93 1F92 8BE6 0D8B C11D

**Comment by Frederick888** [comment]
Just noticed this today. I've TB 102.0.2 on MacBook and it is able to mark lines starting with `> ` as citations in blue after I call `setComposeDetails()`. They are getting ahead of us! 🎉 

So if there are no further questions I'll mark this as resolved.

**Comment by bits-fritz** [comment]
For the records:
This was a thunderbird "feature" which dissapeared for me with thunderbird 102.1.
https://bugzilla.mozilla.org/show_bug.cgi?id=1780281

**Comment by Frederick888** [comment]
@bits-fritz I don't have this issue on 102.3.0.

**Comment by bits-fritz** [comment]
@Frederick888
> @bits-fritz: 
> For the records: This was a thunderbird "feature" which dissapeared for me with thunderbird 102.1. https://bugzilla.mozilla.org/show_bug.cgi?id=1780281

Mhmmm, wrote "dissapeared" with double "s". should read "**disapeared**".
Hope this did not confuse too heavy ;-)

**Comment by nicoroeser** [comment]
Issue is gone for me, too.
Thunderbird 102.2.2, external-editor-revived 0.4.1.

Hooray! :tada:
