### ISSUE TITLE
Editor assumes "Konsole" (KDE) on Linux

### ISSUE THREAD

**Issue by martyheyman** [Frederick888/external-editor-revived#41]
# Description

Running on Ubuntu variant, Pop!_OS. Konsole is not working. Extension is not configurable for anything else. Nothing happens on `^e`. Installed from Thunderbird add-ons page.

# Environment

- AMD64, Linux, Pop!_OS (Ubuntu) 22.04
- Thunderbird version: 91.11.0
- ExtEditorR extension version: 0.2.0
- ExtEditorR host version:  ??? Did not understand the question. I installed it using Thunderbird's installer

# Configuration

Running the Gnome terminal called "Terminal" in the UI: Version 3.44.0 for GNOME 42

# Logs
ExtensionError: No such native application external_editor_revived ExtensionUtils.jsm:58:5
    ExtensionError resource://gre/modules/ExtensionUtils.jsm:58
    startupPromise resource://gre/modules/NativeMessaging.jsm:83

**Comment by Frederick888** [comment]
Read the wiki please.
