### ISSUE TITLE
How to invoke EER from compose window?

### ISSUE THREAD

**Issue by Chris-Hibbert** [Frederick888/external-editor-revived#46]
# Description

The original external editor allowed me to start up an editor from an existing compose window. This allowed my normal flow to be to compose in Thunderbird's window until a message got complex, or required reformatting, or the like, and switch to emacs at that point.

# Environment

- OS: macOS 
- Thunderbird version: 91.11.0 (64-bit)
- ExtEditorR extension version: 0.3.0

# Configuration

```
{
  "name": "external_editor_revived",
  "description": "Edit emails in external editors such as Vim",
  "path": "/users/chris/bin/aquamacs",
  "type": "stdio",
  "allowed_extensions": [
    "external-editor-revived@tsundere.moe"
  ]
}
```

**Comment by Frederick888** [comment]
? There's an External Editor button in composing window, so simply click on it when you feel like it? Is this not what you wanted?

**Comment by Frederick888** [comment]
Why do I even bother having a wiki smh

https://github.com/Frederick888/external-editor-revived/wiki#keyboard-shortcuts
https://github.com/Frederick888/external-editor-revived/wiki#toolbar-buttons
https://github.com/Frederick888/external-editor-revived/wiki#screenshots

**Comment by Chris-Hibbert** [comment]
Thanks for the links.

I now have external-editor-revived in my ~/bin directory, with permissions at 755.
 external_editor_revived.json is in the appropriate MacOS directory with
```
  "name": "external_editor_revived",
  "path": "/Users/chris/bin/external-editor-revived",
```
I have the command template set to 
```
/Applications/Aquamacs.app/Contents/Resources/bin/aquamacs --nofork "/path/to/temp.eml"
```
Each time I hit my keyboard shortcut in an editor window, I see `ExtEditorR sending` in the Error console, but nothing happens in aquamacs.

Further back in the Error Console, I see `ExtensionError: No such native application external_editor_revived`, followed by several copies of 
```
658598585189	addons.webextension.<unknown>	WARN	Loading extension 'null': Reading manifest: Warning processing legacy: An unexpected property was found in the WebExtension manifest.
```

Do you have any suggestions for what I should try next?  I don't know what "No such native application" might indicate.
