### ISSUE TITLE
Revising X-ExtEditorR-* headers

### ISSUE THREAD

**Issue by reagle** [Frederick888/external-editor-revived#51]
Now that I have the plugin working, I have some recommendations on the header messages:

1. Keep them together at the bottom, with the real headers at the top.
2. Fix the mistake in the help header to: "You can though, for example, have two **To**: header lines if there are two recipients"
3. Include blank headers to start, even if not present in TB's composer.
4. Edit for concision.

All-together:

	From: Foo <foo@example.com>
	Subject: I am a test
	To: Bar <bar@example.com>
	Cc:
	Bcc:
	X-ExtEditorR-Send-On-Exit: false
	X-ExtEditorR-Help: Use one address per `To/Cc/Bcc/Reply-To` header
	X-ExtEditorR-Help: (e.g., two recipients requires two `To:` headers).
	X-ExtEditorR-Help: KEEP blank line below to separate headers from body.

	this is a test

	thanks for your help! boo

**Comment by Frederick888** [comment]
1, 3, 4: Good ideas, will do.

2: Already fixed in v0.3.0.
